### ISSUE TITLE
custom command issues

### ISSUE THREAD

**Issue by xiangyu-sun** [dkarchmer/aws-eb-docker-django#2]
when I'm creating a custom command, docker automatically move the management directory to project root. At this time, manage.py will not be able to discovery this command.
Do you have any idea how to fix this?

**Comment by dkarchmer** [comment]
Can you be more specific?
If you look under 'authentication', there is already one management command ('initadmin'), and while the command itself was not working due to a typo in the settings file (which I just fix), the command is running inside the docker container as expected.
If you look at the Dockerfile, I am copying the whole project directory, so everything should be copied as is. Did you make any changes to the Dockerfile?

**Comment by dkarchmer** [comment]
No further action
